### PR TITLE
Build against Numpy 2.0.0rc1 for Python>=3.9

### LINKED ISSUE #80: NumPy 2.0
I don't see any test against numpy 2.0.dev in the CI. Will this package be compatible with numpy 2.0?

### PR DESCRIPTION
**Pull request by astrofrog**
Fixes #80

### CODE REVIEW

**Comment by astrofrog** [comment]
Oh yes good catch!

**Comment by astrofrog** [comment]
I think the easiest fix is going to be to require Python 3.9 or later.

**Comment by dhomeier** [comment]
Thought so too; don't know how exactly the dependencies are resolved in the wheels – on a `pip install fast-histogram` in a fresh env it installs numpy 1.26.4, but also happily installs over a previously installed numpy 2.0.0rc1, with the consequent failure.

**Comment by dhomeier** [comment]
Though maybe requiring in addition `"numpy<<2.0;python_version<='3.8'"]` would make it aware that the wheels are not compatible?

**Comment by astrofrog** [comment]
No I think we will definitely have to bump the minimum to 3.9 - which needs doing anyway.

**Pull request merged**
